spring:
  cloud:
    gateway:
      routes:
        - id: shortlink-admin
          uri: lb://shortlink-admin/api/shortlink/admin/**
          predicates:
            - Path=/api/shortlink/admin/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/shortlink/admin/v1/user/login
                  - /api/shortlink/admin/v1/user/has-username

        - id: shortlink-project
          uri: lb://shortlink-project/api/shortlink/**
          predicates:
            - Path=/api/shortlink/**
          filters:
            - name: TokenValidate